import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Components/Providers";
import { AllProvider } from "./GlobalState/Context";
import ReactQueryProvider from "./GlobalState/ReactQueryProvider";
import ToastProviderComponent from "./Components/ToastProvider";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins font-medium">
        <ReactQueryProvider>
          <Providers>
            <AllProvider>
              <ToastProviderComponent>{children}</ToastProviderComponent>
            </AllProvider>
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
